version: "3"
services:
  product_postgres:
    container_name: product_pg
    image: postgres
    ports:
    - 54321:5432
    environment:
      POSTGRES_PASSWORD: tinhvq

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: product_elasticsearch_01
    ports:
    - 9200:9200
    volumes:
      - data01:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - bootstrap.memory_lock=false
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
volumes:
  data01:
    driver: local